import "./globals.css";
import type { AppProps } from "next/app";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { RainbowProviders } from "./rainbowproviders";
import { ThemeProvider } from "@/components/theme-provider";
import NextAuthSessionProvider from "./sessionProvider";
import Header from "../components/Header";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthSessionProvider>
          <RainbowProviders>
            <Header />
            {children}
            <ToastContainer newestOnTop />
          </RainbowProviders>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
